name: Setup Windows RDP

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: windows-latest
    
    steps:
    - name: Set up environment and enable RDP
      run: |
        Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope Process
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Restart-Service -Name TermService -Force
