name: Windows RDP by Gourav

on: workflow_dispatch:

jobs: build: runs-on: windows-latest

steps:
- name: Download and Setup Ngrok
  run: |
    Invoke-WebRequest -Uri https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
    Expand-Archive -Path ngrok.zip -DestinationPath .
    Move-Item -Path .\ngrok.exe -Destination C:\ngrok.exe

- name: Setup Ngrok Auth Token
  run: C:\ngrok.exe authtoken 2tuJBYHUyucigHIPbwtqvmi91BP_27kpLu9hfXn3YNvyCy9J9

- name: Create User and Enable RDP
  run: |
    net user gouravadmin1 YourPassword123 /add
    net localgroup administrators gouravadmin1 /add
    reg add "HKLM\SYSTEM\CurrentControlSet\Control\Terminal Server" /v fDenyTSConnections /t REG_DWORD /d 0 /f
    Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

- name: Start Ngrok Tunnel (Background)
  shell: pwsh
  run: |
    Start-Job { C:\ngrok.exe tcp 3389 }
    Start-Sleep -Seconds 20

- name: Get RDP Address
  shell: pwsh
  run: |
    $tunnels = Invoke-RestMethod -Uri http://127.0.0.1:4040/api/tunnels
    $rdp_address = $tunnels.tunnels[0].public_url -replace "tcp://", ""
    echo "RDP Address: $rdp_address"

- name: Keep Workflow Alive
  run: timeout /t 14400


